server:
  port: 9002

springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha

ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
